# Generated by Django 2.2 on 2020-05-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200519_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategoryModle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('status', models.BooleanField(default=True, verbose_name='显示状态')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
            ],
            options={
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='ArticleModle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('category_id', models.IntegerField()),
                ('description', models.CharField(max_length=50, verbose_name='文章简介')),
                ('views', models.IntegerField(default=0, verbose_name='阅读量')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('collections', models.IntegerField(default=0, verbose_name='收藏数')),
                ('status', models.BooleanField(default=True, verbose_name='显示状态')),
                ('is_stick', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标识'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_login_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.BooleanField(default=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.IntegerField(default=True, verbose_name='账号状态'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=10, verbose_name='用户名'),
        ),
    ]
