# Generated by Django 2.2 on 2020-05-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200519_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecategorymodle',
            old_name='is_delete',
            new_name='is_del',
        ),
        migrations.RenameField(
            model_name='articlemodle',
            old_name='is_delete',
            new_name='is_del',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='is_delete',
            new_name='is_del',
        ),
    ]
