# Generated by Django 2.2 on 2020-05-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200519_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='last_login_date',
            new_name='last_login_time',
        ),
    ]
